# Generated by Django 4.1.3 on 2022-12-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('extention', models.FileField(upload_to='files')),
                ('userName', models.CharField(max_length=150)),
                ('filesize', models.CharField(max_length=100)),
            ],
        ),
    ]
