# Generated by Django 4.1.3 on 2022-12-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersfiles',
            old_name='extention',
            new_name='file',
        ),
    ]
