# Generated by Django 4.1.3 on 2022-12-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_extention_usersfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfiles',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
