# Generated by Django 4.1.3 on 2022-12-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usersimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersfiles',
            name='filesize',
        ),
        migrations.RemoveField(
            model_name='usersimage',
            name='imagesize',
        ),
    ]
